name: tag changes

on:
  push:
    branches:
      - main
    tags: v*
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: "https://registry.npmjs.org"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: 安装依赖
        run: |
          pnpm install

      - name: 删除 pnpm-lock.yaml
        run: rm -rf pnpm-lock.yaml

      - name: 编译
        run: pnpm build

      - name: 设置时区
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      - name: 删除开发依赖
        run: npm run pr clean

      - name: 删除文件
        run: |
          rm -rf src .github tsconfig.json eslint.config.mjs

      - name: 发布到 npm
        run: npm run pub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          ACTIONS_STEP_DEBUG: false
